spring.application.name=gateway-service
server.port=8090
spring.main.web-application-type=reactive

# TIENDA SERVICE
spring.cloud.gateway.routes[0].id=tienda-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/tiendas/**

# PRODUCTO / CATALOGO SERVICE
spring.cloud.gateway.routes[1].id=catalogo-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/productos/**

# INVENTARIO SERVICE
spring.cloud.gateway.routes[2].id=inventario-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/inventarios/**

# CARRITO SERVICE
spring.cloud.gateway.routes[3].id=carrito-service
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/carrito/**

# PEDIDO SERVICE
spring.cloud.gateway.routes[4].id=pedido-service
spring.cloud.gateway.routes[4].uri=http://localhost:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/pedidos/**

# PAGO SERVICE
spring.cloud.gateway.routes[5].id=pago-service
spring.cloud.gateway.routes[5].uri=http://localhost:8086
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/pagos/**

# VENTA / FACTURACION SERVICE
spring.cloud.gateway.routes[6].id=venta-service
spring.cloud.gateway.routes[6].uri=http://localhost:8087
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/ventas-facturas/**

# SOPORTE SERVICE
spring.cloud.gateway.routes[7].id=soporte-service
spring.cloud.gateway.routes[7].uri=http://localhost:8088
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/tickets/**

# USUARIO SERVICE
spring.cloud.gateway.routes[8].id=usuario-service
spring.cloud.gateway.routes[8].uri=http://localhost:8089
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/usuarios/**

# AUTH SERVICE
spring.cloud.gateway.routes[9].id=auth-service
spring.cloud.gateway.routes[9].uri=http://localhost:8091
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/auth/**